name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/kenzaelkouhen-patch-1  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ghost-app .

      - name: Tag Docker image
        run: |
          docker tag ghost-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ghost-app-repo:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ghost-app-repo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init

      - name: Terraform Apply
        run: |
          cd infrastructure
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

